export const department = [
  'Sales',
  'Marketing',
  'Engineering',
  'Human Resouces',
  'Legal'
]

export const stateUSA = [
  'Alabama',
  'Alaska',
  'American Samoa',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District of Columbia',
  'Federated States of Micronesia',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Marshall Islands',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Northern Mariana Islands',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Palau',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virgin Island',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
]

// const products = [
//   { id: 1, name: 'Cheese', price: 4.9, stock: 20 },
//   { id: 2, name: 'Milk', price: 1.9, stock: 32 },
//   { id: 3, name: 'Yoghurt', price: 2.4, stock: 12 },
//   { id: 4, name: 'Heavy Cream', price: 3.9, stock: 9 },
//   { id: 5, name: 'Butter', price: 0.9, stock: 99 },
//   { id: 6, name: 'Sour Cream ', price: 2.9, stock: 86 },
//   { id: 7, name: 'Fancy French Cheese 🇫🇷', price: 99, stock: 12 }
// ]

// https://codepen.io/learnwebcode/pen/Exaqbvx?editors=1010
